name = "Document Center Service"

[author]
name = "Le Khac Man"
email = "khacmanle gmail dot com"

[db]
host = "localhost"
port = "5432"
name = "dms"
user = "dms"
password = "dms123"

[app]
port = "8001"
loglevel = 'trace'
